DEFAULT_CATEGORIES = {
    "Income": ["Salary", "Freelance", "Bonus", "Refund", "Other income"],
    "Groceries": ["Market", "Supermarket", "Organic store", "Delivery"],
    "Transport": ["Public transport", "Uber / Taxi", "Lime / scooters", "Fuel"],
    "Trips / Travel": ["Flights", "Hotels", "Activities"],
    "Entertainment": ["Cinema", "Streaming", "Events"],
    "House / Rent / Mortgage": ["Rent", "Mortgage", "Condominium"],
    "Bills": ["Electricity", "Water", "Gas", "Internet / WiFi", "Phone"],
    "Insurance": ["Home", "Health", "Car"],
    "Health / Medical": ["Doctor", "Pharmacy", "Gym"],
    "Dining Out": ["Restaurants", "Coffee", "Bars"],
    "Shopping": ["Clothes", "Personal items", "Home items"],
    "Subscriptions": ["Netflix", "Spotify", "Cloud"],
    "Savings": ["Emergency fund", "Short-term savings", "Remaining from income"],
    "Investments": ["ETF", "Pension", "Brokerage"],
    "Miscellaneous": ["Other"],
}

CATEGORY_GROUPS = {
    "Income": "Income",
    "Groceries": "Variable",
    "Transport": "Variable",
    "Trips / Travel": "Variable",
    "Entertainment": "Variable",
    "House / Rent / Mortgage": "Fixed",
    "Bills": "Fixed",
    "Insurance": "Fixed",
    "Health / Medical": "Variable",
    "Dining Out": "Variable",
    "Shopping": "Variable",
    "Subscriptions": "Fixed",
    "Savings": "Savings & Investments",
    "Investments": "Savings & Investments",
    "Miscellaneous": "Variable",
}

CATEGORY_ICONS = {
    "Income": "💶",
    "Groceries": "🛒",
    "Transport": "🚗",
    "Trips / Travel": "✈️",
    "Entertainment": "🎬",
    "House / Rent / Mortgage": "🏠",
    "Bills": "💡",
    "Insurance": "🛡️",
    "Health / Medical": "🩺",
    "Dining Out": "🍽️",
    "Shopping": "🛍️",
    "Subscriptions": "🔁",
    "Savings": "🐷",
    "Investments": "📈",
    "Miscellaneous": "📌",
}
